#!/usr/bin/env tsx
/**
 * generate-redact-paths.ts — SOC2-CC7-016
 *
 * Source of truth: `apps/api/prisma/schema.prisma`.
 *
 * Walks the schema, finds every field annotated with `/// @pii`, and emits
 * Pino-compatible redact path strings covering the shapes Prisma will return:
 *
 *   • model_lower.field                 (direct fetch)
 *   • model_lower[*].field              (findMany / arrays)
 *   • *.field                           (defense-in-depth: any container at depth 1)
 *   • *[*].field                        (defense-in-depth: any array of objects)
 *   • *.model_lower.field               (single nested include)
 *   • *.model_lower[*].field            (1-to-many nested include)
 *
 * Output: apps/api/src/config/pii-redact-paths.generated.ts
 *
 * Re-run whenever a /// @pii annotation is added or removed:
 *   pnpm --filter api redact:generate
 *
 * CI fitness function: a pre-commit / CI check compares the committed
 * generated file with a fresh run; drift fails the build.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

const SCHEMA_PATH = join(__dirname, '..', 'prisma', 'schema.prisma');
const OUTPUT_PATH = join(__dirname, '..', 'src', 'config', 'pii-redact-paths.generated.ts');

interface PiiField {
  model: string;
  field: string;
}

function parseSchema(src: string): PiiField[] {
  const out: PiiField[] = [];
  const lines = src.split('\n');

  let currentModel: string | null = null;
  let braceDepth = 0;
  let pendingPii = false;

  for (let i = 0; i < lines.length; i++) {
    const rawLine = lines[i];
    const line = rawLine.trim();

    // Model start: `model Foo {`
    const modelMatch = line.match(/^model\s+([A-Za-z0-9_]+)\s*\{/);
    if (modelMatch) {
      currentModel = modelMatch[1];
      braceDepth = 1;
      pendingPii = false;
      continue;
    }

    if (currentModel === null) continue;

    // Track braces so we know when we leave a model body
    for (const ch of line) {
      if (ch === '{') braceDepth++;
      else if (ch === '}') braceDepth--;
    }
    if (braceDepth <= 0) {
      currentModel = null;
      pendingPii = false;
      continue;
    }

    // Triple-slash @pii annotation
    if (line.startsWith('///')) {
      const body = line.slice(3).trim();
      if (body === '@pii' || body.startsWith('@pii ')) {
        pendingPii = true;
      }
      continue;
    }

    // Skip blank lines and block-level constraints (@@) without resetting flag
    if (line.length === 0) continue;
    if (line.startsWith('//')) continue;
    if (line.startsWith('@@')) continue;

    // Field line: starts with identifier
    const fieldMatch = line.match(/^([A-Za-z_][A-Za-z0-9_]*)\s+/);
    if (fieldMatch && pendingPii) {
      out.push({ model: currentModel, field: fieldMatch[1] });
      pendingPii = false;
    } else if (fieldMatch) {
      // A non-tagged field consumes the pending state too (defensive)
      pendingPii = false;
    }
  }

  return out;
}

function lowerCamel(s: string): string {
  return s.charAt(0).toLowerCase() + s.slice(1);
}

function buildPaths(piiFields: PiiField[]): string[] {
  const paths = new Set<string>();

  // Generic defense-in-depth: any container at depth 1, any array.
  // These are model-agnostic — they cover unexpected serialisation shapes
  // (e.g. logging `{ data: row }`, `{ rows: [...] }`, axios-style wrappers).
  const uniqueFieldNames = new Set(piiFields.map((p) => p.field));
  for (const field of uniqueFieldNames) {
    paths.add(`*.${field}`);
    paths.add(`*[*].${field}`);
  }

  // Model-shaped paths. Pino redact only supports `*` as a leading wildcard
  // segment; explicit model.field strings cover the common direct-log case.
  for (const { model, field } of piiFields) {
    const m = lowerCamel(model);
    paths.add(`${m}.${field}`);
    paths.add(`${m}[*].${field}`);
    paths.add(`*.${m}.${field}`);
    paths.add(`*.${m}[*].${field}`);

    // Plural collection wrappers commonly used in handler responses
    // (e.g. `{ applications: [...] }` from a findMany).
    const plural = m.endsWith('s') ? `${m}es` : `${m}s`;
    paths.add(`${plural}[*].${field}`);
    paths.add(`*.${plural}[*].${field}`);
  }

  return Array.from(paths).sort();
}

function emitTs(paths: string[], piiFields: PiiField[]): string {
  const stamp = new Date().toISOString();
  const inventory = piiFields
    .map((p) => `//   ${p.model}.${p.field}`)
    .sort()
    .join('\n');

  return `// AUTO-GENERATED — DO NOT EDIT BY HAND.
// Generated by: apps/api/scripts/generate-redact-paths.ts
// Source:       apps/api/prisma/schema.prisma  (/// @pii annotations)
// Regenerate:   pnpm --filter api redact:generate
//
// SOC2-CC7-016: Model-driven Pino redaction. This file is the type-derived
// half of the redaction list; \`logger.ts\` unions it with the hand-curated
// list (header tokens, env-var names, etc.) for defense in depth.
//
// PII inventory (${piiFields.length} fields):
${inventory}
//
// Generated at: ${stamp}

export const GENERATED_PII_REDACT_PATHS: readonly string[] = ${JSON.stringify(
    paths,
    null,
    2,
  )} as const;
`;
}

function main(): void {
  const src = readFileSync(SCHEMA_PATH, 'utf8');
  const piiFields = parseSchema(src);

  if (piiFields.length === 0) {
    // eslint-disable-next-line no-console
    console.error(
      '[redact:generate] No /// @pii annotations found. Refusing to write an empty redact list.',
    );
    process.exit(1);
  }

  const paths = buildPaths(piiFields);
  const ts = emitTs(paths, piiFields);
  writeFileSync(OUTPUT_PATH, ts, 'utf8');

  // eslint-disable-next-line no-console
  console.log(
    `[redact:generate] wrote ${paths.length} redact paths from ${piiFields.length} PII fields -> ${OUTPUT_PATH}`,
  );
}

main();
